// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_tables_simpleplace_simplecity_simplemember_and_mod_fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_tables_simpleplace_simplecity_simplemember_and_mod_fields));
        
        string IMigrationMetadata.Id
        {
            get { return "202108111910255_added_tables_simpleplace_simplecity_simplemember_and_mod_fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
