// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_pay_fields_to_simplemember : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_pay_fields_to_simplemember));
        
        string IMigrationMetadata.Id
        {
            get { return "202109081015324_added_pay_fields_to_simplemember"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
