// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rename_table_rents_to_rent : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rename_table_rents_to_rent));
        
        string IMigrationMetadata.Id
        {
            get { return "202108170731080_rename_table_rents_to_rent"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
