// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_field_place_to_table_tournamentgrouptableitem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_field_place_to_table_tournamentgrouptableitem));
        
        string IMigrationMetadata.Id
        {
            get { return "202108020820353_added_field_place_to_table_tournament-group-table-item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
