// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_field_length_from_table_match_and_add_it_to_tournamentgroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_field_length_from_table_match_and_add_it_to_tournamentgroup));
        
        string IMigrationMetadata.Id
        {
            get { return "202107291242217_remove_field_length_from_table_match_and_add_it_to_tournament-group"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
