// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class drop_place_field_from_table_simplecollect : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(drop_place_field_from_table_simplecollect));
        
        string IMigrationMetadata.Id
        {
            get { return "202108101323401_drop_place_field_from_table_simple-collect"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
