// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_field_when_costperhour_to_table_worktime_field_worktime_to_simpleplace : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_field_when_costperhour_to_table_worktime_field_worktime_to_simpleplace));
        
        string IMigrationMetadata.Id
        {
            get { return "202108161638411_added_field_when_costperhour_to_table_worktime_field_worktime_to_simpleplace"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
