// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fieldPlaceIdinMatchestablecanbenull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fieldPlaceIdinMatchestablecanbenull));
        
        string IMigrationMetadata.Id
        {
            get { return "202107051500468_field-PlaceId-in-Matches-table-can-be-null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
