// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class replace_field_matchlength_from_table_tournamentgroup_to_tournaments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(replace_field_matchlength_from_table_tournamentgroup_to_tournaments));
        
        string IMigrationMetadata.Id
        {
            get { return "202107301514265_replace_field_matchlength_from_table_tournament-group_to_tournaments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
