// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changebidteamtotournamenttournamenttotournamentgroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changebidteamtotournamenttournamenttotournamentgroup));
        
        string IMigrationMetadata.Id
        {
            get { return "202105082020597_change-bidteamtotournament-tournament-to-tournamentgroup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
