// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class make_nullable_fields_in_tournamentgrouptableitem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(make_nullable_fields_in_tournamentgrouptableitem));
        
        string IMigrationMetadata.Id
        {
            get { return "202107221641098_make_nullable_fields_in_tournamentgrouptableitem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
