// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_fileds_to_Match_table_which_identificates_teams_by_bids_to_tournaments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_fileds_to_Match_table_which_identificates_teams_by_bids_to_tournaments));
        
        string IMigrationMetadata.Id
        {
            get { return "202107191621395_added_fileds_to_Match_table_which_identificates_teams_by_bids_to_tournaments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
