// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_table_for_tournament_game_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_table_for_tournament_game_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "202107191600347_added_table_for_tournament_game_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
