// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_field_fullprice_and_change_datatype_cost_in_simplecollect : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_field_fullprice_and_change_datatype_cost_in_simplecollect));
        
        string IMigrationMetadata.Id
        {
            get { return "202110011145485_add_field_fullprice_and_change_datatype_cost_in_simplecollect"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
