// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_basemodel_fields_tosimplecollect_simpleplace : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_basemodel_fields_tosimplecollect_simpleplace));
        
        string IMigrationMetadata.Id
        {
            get { return "202108130646432_add_basemodel_fields_tosimplecollect_simpleplace"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
