// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_fields_length_and_played_to_table_match : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_fields_length_and_played_to_table_match));
        
        string IMigrationMetadata.Id
        {
            get { return "202107291238253_added_fields_length_and_played_to_table_match"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
