// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_table_simplecollects_and_field_simplecollectscollection_in_table_userprofile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_table_simplecollects_and_field_simplecollectscollection_in_table_userprofile));
        
        string IMigrationMetadata.Id
        {
            get { return "202108091527541_added_table_simple-collects_and_field_simple-collects-collection_in_table_userprofile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
