// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_connected_fields_to_table_Break_and_Worktime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_connected_fields_to_table_Break_and_Worktime));
        
        string IMigrationMetadata.Id
        {
            get { return "202109141644217_added_connected_fields_to_table_Break_and_Worktime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
