// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class del_fields_from_table_TournamentGroupTableItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(del_fields_from_table_TournamentGroupTableItem));
        
        string IMigrationMetadata.Id
        {
            get { return "202107201714495_del_fields_from_table_TournamentGroupTableItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
