// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TournamentGroupfieldinMatchandchdngesinconstructors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TournamentGroupfieldinMatchandchdngesinconstructors));
        
        string IMigrationMetadata.Id
        {
            get { return "202106171043526_TournamentGroup field in Match and chdnges in constructors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
