// <auto-generated />
namespace osbackend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addnameandlinkfieldstotournamentanduserprofile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnameandlinkfieldstotournamentanduserprofile));
        
        string IMigrationMetadata.Id
        {
            get { return "202201071028406_add-name-and-link-fields-to-tournament-and-userprofile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
